SELECT
  BATCHNAME AS BATCH_NAME,
  PODURL AS POD_URL,
  PODNAME AS POD_NAME,
  NVL(CD_LAST_UPDATED, CS_LAST_UPDATED) AS LAST_UPDATED
FROM
  (
    SELECT
      UBR.CNV_BATCH AS BATCHNAME,
      UBR.POD_URL AS PODURL,
      UP.POD_NAME AS PODNAME,
      MAX(CD.LAST_UPDATE_DATE) AS CD_LAST_UPDATED,
      MAX(CS.LAST_UPDATE_DATE) AS CS_LAST_UPDATED
    FROM
      CNV_DATA CD,
      CNV_SPREADSHEET CS,
      UX_BATCH_REQUEST UBR,
      UX_POD UP
    WHERE
      1 = 1
      AND CD.CNV_BATCH = CS.CNV_BATCH(+)
      AND CD.CNV_BATCH = UBR.CNV_BATCH
      AND UP.POD_URL = UBR.POD_URL
    GROUP BY
      UBR.CNV_BATCH,
      UBR.POD_URL,
      UP.POD_NAME
  )