SELECT
  UBR.UX_BATCH_REQUEST_ID,
  UBR.POD_URL,
  UBR.CNV_BATCH,
  UBR.CREATED_BY,
  UBR.CREATED_ON,
  UBR.UPDATED_BY,
  UBR.UPDATED_ON,
  UP.POD_NAME
FROM
  UX_BATCH_REQUEST UBR,
  UX_POD UP
WHERE
  1 = 1
  AND UBR.POD_URL = UP.POD_URL
  AND UBR.CNV_BATCH IN (
    SELECT
      CNV_BATCH
    FROM
      CNV_SPREADSHEET
  )